echo "Installing Extensions for Visual Studio Code"

code --install-extension anseki.vscode-color
code --install-extension austin.code-gnu-global
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension Framer.framer-syntax
code --install-extension johnpapa.vscode-peacock
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension karigari.chat
code --install-extension markskelton.one-dark-pro-italic
code --install-extension mikestead.dotenv
code --install-extension mrcrowl.hg
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension naumovs.color-highlight
code --install-extension nedy.lights-out
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension Prisma.vscode-graphql
code --install-extension rbbit.typescript-hero
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension ryu1kn.text-marker
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension vscodevim.vim
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.material-theme
